package nobitex

// Generated by https://quicktype.io

type MarketPrice struct {
	Status string `json:"status"`
	Stats  Stats  `json:"stats"`
	Global Global `json:"global"`
}

type Global struct {
	Binance map[string]float64 `json:"binance"`
}

type Stats struct {
	UsdtRls UsdtRls `json:"usdt-rls"`
}

type UsdtRls struct {
	IsClosed  bool   `json:"isClosed"`
	BestSell  string `json:"bestSell"`
	BestBuy   string `json:"bestBuy"`
	VolumeSrc string `json:"volumeSrc"`
	VolumeDst string `json:"volumeDst"`
	Latest    string `json:"latest"`
	DayLow    string `json:"dayLow"`
	DayHigh   string `json:"dayHigh"`
	DayOpen   string `json:"dayOpen"`
	DayClose  string `json:"dayClose"`
	DayChange string `json:"dayChange"`
}
