version: '3'

services:
  tp:
    hostname: TP
    container_name: tp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6004:6004
    environment:
      - PORT=6004
      - REDIS_URL=redis://redis:6379/5
      - GIN_MODE=debug
    networks:
      - tp_net
      - redis_db

networks:
  redis_db:
    external:
      name: redis_db
  tp_net:
    driver: bridge
    name: tp_net
