// Generated by https://quicktype.io
package simplecmc

import "TP/schema"

type Currency string

type CMCListResp struct {
	Status Status `json:"status"`
	Data   []Coin `json:"data"`
}

type Status struct {
	Timestamp    string      `json:"timestamp"`
	ErrorCode    int64       `json:"error_code"`
	ErrorMessage interface{} `json:"error_message"`
	Elapsed      int64       `json:"elapsed"`
	CreditCount  int64       `json:"credit_count"`
	Notice       interface{} `json:"notice"`
	TotalCount   int64       `json:"total_count"`
}

type Coin struct {
	ID                  int64              `json:"id"`
	Rank                int64              `json:"rank"`
	Name                string             `json:"name"`
	Symbol              string             `json:"symbol"`
	Slug                string             `json:"slug"`
	Tags                []string           `json:"tags"`
	IsActive            int64              `json:"is_active"`
	FirstHistoricalData string             `json:"first_historical_data"`
	LastHistoricalData  string             `json:"last_historical_data"`
	Platform            *schema.Platform   `json:"platform"`
	Quote               map[Currency]Quote `json:"quote"`
}

type Quote struct {
	Price                 float64  `json:"price"`
	Volume24H             float64  `json:"volume_24h"`
	VolumeChange24H       float64  `json:"volume_change_24h"`
	PercentChange1H       float64  `json:"percent_change_1h"`
	PercentChange24H      float64  `json:"percent_change_24h"`
	PercentChange7D       float64  `json:"percent_change_7d"`
	PercentChange30D      float64  `json:"percent_change_30d"`
	PercentChange60D      float64  `json:"percent_change_60d"`
	PercentChange90D      float64  `json:"percent_change_90d"`
	MarketCap             float64  `json:"market_cap"`
	MarketCapDominance    float64  `json:"market_cap_dominance"`
	FullyDilutedMarketCap float64  `json:"fully_diluted_market_cap"`
	Tvl                   *float64 `json:"tvl"`
	LastUpdated           string   `json:"last_updated"`
}
