/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

// An object containing various resource URLs for this cryptocurrency.
type CryptocurrenciesInfoUrlsObject struct {
	Website      *[]string `json:"website"`
	TechnicalDoc *[]string `json:"technical_doc"`
	Explorer     *[]string `json:"explorer"`
	SourceCode   *[]string `json:"source_code"`
	MessageBoard *[]string `json:"message_board"`
	Chat         *[]string `json:"chat"`
	Announcement *[]string `json:"announcement"`
	Reddit       *[]string `json:"reddit"`
	Twitter      *[]string `json:"twitter"`
}
