/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

// Internal Server Error
type HttpStatus500ErrorObject struct {
	Status *ErrorStatus `json:"status,omitempty"`
}
