/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

// Metadata about the parent cryptocurrency platform this cryptocurrency belongs to if it is a token, otherwise null.
type Platform struct {
	// The unique CoinMarketCap ID for the parent platform cryptocurrency.
	Id int32 `json:"id"`
	// The name of the parent platform cryptocurrency.
	Name string `json:"name"`
	// The ticker symbol for the parent platform cryptocurrency.
	Symbol string `json:"symbol"`
	// The web URL friendly shorthand version of the parent platform cryptocurrency name.
	Slug string `json:"slug"`
	// The token address on the parent platform cryptocurrency.
	TokenAddress string `json:"token_address"`
}
