/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

import (
	"time"
)

type ErrorStatus struct {
	// Current ISO 8601 timestamp on the server.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// An internal error code string for the current error. If a unique platform error code is not available the HTTP status code is returned.
	ErrorCode int32 `json:"error_code,omitempty"`
	// An error message to go along with the error code.
	ErrorMessage string `json:"error_message,omitempty"`
	// Number of milliseconds taken to generate this response
	Elapsed int32 `json:"elapsed,omitempty"`
	// Number of API call credits required for this call. Always 0 for errors.
	CreditCount int32 `json:"credit_count,omitempty"`
}
