/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

import (
	"time"
)

// A cryptocurrency object for every cryptocurrency that matched list options.
type CryptocurrencyListingsLatestCryptocurrencyObject struct {
	// The unique CoinMarketCap ID for this cryptocurrency.
	Id int32 `json:"id,omitempty"`
	// The name of this cryptocurrency.
	Name string `json:"name,omitempty"`
	// The ticker symbol for this cryptocurrency.
	Symbol string `json:"symbol,omitempty"`
	// The web URL friendly shorthand version of this cryptocurrency name.
	Slug string `json:"slug,omitempty"`
	// The cryptocurrency's CoinMarketCap rank by market cap.
	CmcRank int32 `json:"cmc_rank,omitempty"`
	// The number of active trading pairs available for this cryptocurrency across supported exchanges.
	NumMarketPairs int32 `json:"num_market_pairs,omitempty"`
	// The approximate number of coins circulating for this cryptocurrency.
	CirculatingSupply float64 `json:"circulating_supply,omitempty"`
	// The approximate total amount of coins in existence right now (minus any coins that have been verifiably burned).
	TotalSupply float64 `json:"total_supply,omitempty"`
	// The market cap by total supply. *This field is only returned if requested through the `aux` request parameter.*
	MarketCapByTotalSupply float64 `json:"market_cap_by_total_supply,omitempty"`
	// The expected maximum limit of coins ever to be available for this cryptocurrency.
	MaxSupply float64 `json:"max_supply,omitempty"`
	// Timestamp (ISO 8601) of the last time this cryptocurrency's market data was updated.
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// Timestamp (ISO 8601) of when this cryptocurrency was added to CoinMarketCap.
	DateAdded time.Time                                           `json:"date_added,omitempty"`
	Tags      *[]string                                           `json:"tags,omitempty"`
	Platform  *Platform                                           `json:"platform,omitempty"`
	Quote     *map[string]CryptocurrencyListingsLatestQuoteObject `json:"quote,omitempty"`
}
