/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

import (
	"time"
)

// Cryptocurrency object for each result
type CryptocurrencyMapCryptocurrencyObject struct {
	// The unique cryptocurrency ID for this cryptocurrency.
	Id int32 `json:"id"`
	// The name of this cryptocurrency.
	Name string `json:"name"`
	// The ticker symbol for this cryptocurrency, always in all caps.
	Symbol string `json:"symbol"`
	// The web URL friendly shorthand version of this cryptocurrency name.
	Slug string `json:"slug"`
	// 1 if this cryptocurrency has at least 1 active market currently being tracked by the platform, otherwise 0. A value of 1 is analogous with `listing_status=active`.
	IsActive int32  `json:"is_active,omitempty"`
	Status   string `json:"status,omitempty"`
	// Timestamp (ISO 8601) of the date this cryptocurrency was first available on the platform.
	FirstHistoricalData time.Time `json:"first_historical_data,omitempty"`
	// Timestamp (ISO 8601) of the last time this cryptocurrency's market data was updated.
	LastHistoricalData time.Time `json:"last_historical_data,omitempty"`
	Platform           *Platform `json:"platform,omitempty"`
}
