/*
 * CoinMarketCap Cryptocurrency API Documentation
 *
 * CoinMarketCap API
 *
 * API version: 1.26.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cmc

import (
	"time"
)

// A results object for each cryptocurrency requested. The map key being the id/symbol used in the request.
type CryptocurrenciesInfoCryptocurrencyObject struct {
	// The unique CoinMarketCap ID for this cryptocurrency.
	Id int32 `json:"id"`
	// The name of this cryptocurrency.
	Name string `json:"name"`
	// The ticker symbol for this cryptocurrency.
	Symbol string `json:"symbol"`
	// The category for this cryptocurrency.
	Category string `json:"category"`
	// The web URL friendly shorthand version of this cryptocurrency name.
	Slug string `json:"slug"`
	// Link to a CoinMarketCap hosted logo png for this cryptocurrency. 64px is default size returned. Replace \"64x64\" in the image path with these alternative sizes: 16, 32, 64, 128, 200
	Logo string `json:"logo"`
	// A CoinMarketCap supplied brief description of this cryptocurrency. This field will return null if a description is not available.
	Description string `json:"description"`
	// Timestamp (ISO 8601) of when this cryptocurrency was added to CoinMarketCap.
	DateAdded time.Time `json:"date_added"`
	// A [Markdown](https://commonmark.org/help/) formatted notice that may highlight a significant event or condition that is impacting the cryptocurrency or how it is displayed, otherwise null. A notice may highlight a recent or upcoming mainnet swap, symbol change, exploit event, or known issue with a particular exchange or market, for example. If present, this notice is also displayed in an alert banner at the top of the cryptocurrency's page on coinmarketcap.com.
	Notice   string                          `json:"notice"`
	Tags     *[]string                       `json:"tags"`
	Platform *Platform                       `json:"platform"`
	Urls     *CryptocurrenciesInfoUrlsObject `json:"urls"`
}
