package schema

// Generated by https://quicktype.io

type Platforms []Platform

type Platform struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Symbol       string `json:"symbol"`
	Slug         string `json:"slug"`
	TokenAddress string `json:"token_address"`
	ChainID      int64  `json:"chainId"`
}
